### ISSUE TITLE
make内存泄露

### ISSUE THREAD

**Issue by sonichy** [ShawZG/xWeather#1]
Deepin15_Qt5.7
Deepin20.3_Qt5.15.1
![alt](https://z3.ax1x.com/2021/11/29/oMX1w8.png)

**Comment by ShawZG** [comment]
之前确实没有关注过这个，看了下，好像就是编译Qt的资源文件内存里面升上去了，编译结束也释放了。之前偷懒，项目里把一个字体库也添加进资源文件了。
